name: Hoitinga Â· van Zwieten
shortname: HvZ
author: HvZ Engineering
email: info@hvzengineering.nl
domain: hvzengineering.nl

markdown: redcarpet
pygments: true
paginate: 5
permalink: none

tabs:
  - title: Home
    url: /

  - title: What we do
    url: /whatwedo.html

  - title: Who we are
    url: /whoweare.html

  - title: References
    url: /references.html

  - title: Contact
    url: /contact.html
